### PR TITLE
Add polynomial unit tests

### PR DESCRIPTION
**Pull request by DelevoXDG**
Test all methods of polynomial class

### CODE REVIEW

**Comment by Herman0802** [comment]
1. Add a description to each test;
2. Place all tests in the order in which the functions being tested go; 
3. Add a blank line between lines 1 and 2, as well as lines 5 and 6;

**Review by Herman0802 — COMMENTED** [review]
1. Add a description to each test;
2. Place all tests in the order in which the functions being tested go;
3. Add a blank line between lines 1 and 2, as well as lines 5 and 6;

**Comment by DelevoXDG** [comment]
> Place all tests in the order in which the functions being tested go;

Why?

**Review by Herman0802 — COMMENTED** [review]
Everything is fine 👍

**Comment by Herman0802** [comment]
FYI, I think the best solution would be to do a `Squash and merge`

**Review by Herman0802 — APPROVED** [review]

**Pull request merged**
